# vim: set ft=ansible:
---

# Tasks to be executed only in the localhost server
- name: Step 01 local host preparation for Mobile deployment
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - generate_ansible_hosts_file
  tasks:
    - name: generate ansible hosts file
      template:
        src: "../configs/{{ env_type }}/files/hosts_template.j2"
        dest: "../workdir/hosts-{{ env_type }}-{{ guid }}"

# Tasks to be executed only in the bastion server
# 2.1. Install the RHMAP OpenShift Templates
- name: Step 02 bastion preparation for Mobile deployment
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  become: true
  gather_facts: False
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - rhmap_host_templates
  tasks:
    - name: Ensure directory /etc/ansible exists
      file:
        path: /etc/ansible
        state: directory

    - name: Copy over ansible hosts file
      copy:
        src: "../workdir/hosts-{{ env_type }}-{{ guid }}"
        dest: "{{ hosts_rhmap }}"

    # Enabling RHM repos
    - name: Enable Red Hat Mobile repos
      shell: subscription-manager repos --enable="{{ rhmap_repo }}"

    # Installing templates
    - name: Install templates & playbooks on bastion
      yum:  
        name: "rhmap-fh-openshift-templates"
        state: latest

    # 2.2.2. Setting Up an Inventory File
    - name: Setup ansible inventory for RHMAP
      template:
        src: hosts_rhmap
        dest: /etc/ansible/hosts_rhmap
        mode: 0640

    # 2.3. Seeding the Nodes with the RHMAP Images 
    - block:
      - name: Seed rhmap core docker images to nodes
        shell: |
          ANSIBLE_ROLES_PATH=/opt/rhmap/"{{ rhmap_version}}"/rhmap-installer/roles/ \
          ansible-playbook -i {{ hosts_rhmap }} /opt/rhmap/"{{ rhmap_version}}"/rhmap-installer/playbooks/seed-images.yml \
          -e "project_type=core" \
          -e "rhmap_version='{{ rhmap_version }}'" > /tmp/rhmap-seed-core.out 2>&1
        async: 5400
        poll: 30
        register: seed_core

      - fail: msg="Failed to seed core images to nodes. Check log output /tmp/rhmap-seed-core.out"
        when: seed_core.rc is undefined or seed_core.rc != 0
    
    - block:
      - name: Seed rhmap mbaas docker images to nodes
        shell: |
          ANSIBLE_ROLES_PATH=/opt/rhmap/"{{ rhmap_version}}"/rhmap-installer/roles/ \
          ansible-playbook -i {{ hosts_rhmap }} /opt/rhmap/"{{ rhmap_version}}"/rhmap-installer/playbooks/seed-images.yml \
          -e "project_type=mbaas" \
          -e "rhmap_version='{{ rhmap_version }}'" > /tmp/rhmap-seed-mbaas 2>&1
        async: 5400
        poll: 30
        register: seed_mbaas

      - fail: msg="Failed to seed mbaas images to nodes. Check log output /tmp/rhmap-seed-mbaas.out"
        when: seed_mbaas.rc is undefined or seed_mbaas.rc != 0
      
#########################Configuring mobile-nodes
# Tasks to be excute on all nodes
# See: https://access.redhat.com/documentation/en-us/red_hat_mobile_application_platform/4.5/html/installing_rhmap/preparing-infrastructure-for-installation
- name: Configuring mobile-nodes
  gather_facts: False
  become: yes
  hosts:
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_node') | replace('-', '_') }}"
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_master') | replace('-', '_') }}"
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  tasks:
  # Activate subscription-manager  
  - name: Check subscription status on all nodes
    shell: subscription-manager status
    register: subs
    ignore_errors: yes
  - set_fact:
      subs_status={{ true if (subs.stdout | search("Current")) else false }}
  - name: Subscribe nodes
    shell: subscription-manager register --username="{{ rhn_username }}" --password="{{ rhn_password }}"
    when: subs_status|bool == false
  
  # Attach RHM POOL ID
  - name: Get Red Hat Mobile pool ID
    shell: subscription-manager list --available --matches=*Mobile* --pool-only | head -1 -
    register: rhmap_pool_id
    run_once: true
  - name: Attach pool ID ( "{{ rhmap_pool_id.stdout }}" ) on all hosts
    shell: subscription-manager attach --pool="{{ rhmap_pool_id.stdout }}"

  # Refresh certificates
  - name: Refresh certificates
    shell: subscription-manager refresh
  tags:
    - mobile_node_tasks


######################### Configuring storage for mobile

- name: Configuring storage for mobile
  gather_facts: False
  become: yes
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_support') | replace('-', '_') }}"
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  roles:
    - { role: "../roles/mobile-storage", dir: '/opt/a', app_port: 5000 }
  tags:
    - mobile_storage

######################### Run Mobile Installer

- name: Run Mobile Installer
  gather_facts: False
  become: yes
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  tags:
    - installing_mobile
  tasks:
    - name: Add log path to Ansible configuration
      lineinfile:
        regexp: "^#log_path"
        dest: "/etc/ansible/ansible.cfg"
        line: "log_path = /root/ansible.log"
        state: present
      tags:
        - ansible_log_enable

    # Deploy Core
    - block:
      - name: Deploy Red Hat Mobile Core
        shell: |
          ANSIBLE_ROLES_PATH=/opt/rhmap/"{{ rhmap_version }}"/rhmap-installer/roles/ \
          ansible-playbook -i {{ hosts_rhmap }} /opt/rhmap/{{ rhmap_version }}/rhmap-installer/playbooks/core.yml \
            -e "strict_mode=false" > /tmp/rhmap-deploy-core.out 2>&1
        async: 5400
        poll: 30
        register: install_core
        tags:
        - mobile_installer

      - fail: msg="Failed to install RHMAP Core. Check log output /tmp/rhmap-deploy-core.out"
        when: install_core.rc is undefined or install_core.rc != 0

    # Deploy MBaaS
    - block:
      - name: Deploy Red Hat Mobile MBaaS
        shell: |
          ANSIBLE_ROLES_PATH=/opt/rhmap/"{{ rhmap_version }}"/rhmap-installer/roles/ \
          ansible-playbook -i {{ hosts_rhmap }} /opt/rhmap/{{ rhmap_version }}/rhmap-installer/playbooks/1-node-mbaas.yml \
            -e "strict_mode=false" --skip-tags "label" > /tmp/rhmap-deploy-mbaas.out 2>&1'
        async: 5400
        poll: 30
        register: install_mbaas
        tags:
        - mobile_installer

      - fail: msg="Failed to install RHMAP Core. Check log output /tmp/rhmap-deploy-mbaas.out"
        when: install_mbaas.rc is undefined or install_mbaas.rc != 0

    - name: Fetch ansible.log
      fetch:
        src: /root/ansible.log
        dest: "{{ANSIBLE_REPO_PATH}}/workdir/{{project_tag}}.bastion.ansible.log"
        flat: true
      tags:
        - openshift_installer

    - name: report Byo Playbook error
      fail:
        msg: "FAIL {{ project_tag }} byo/config failed"
      when: openshift_install_log|failed
      tags:
        - mobile_installer