---

- block:
    - name: register redis instances
      debug: msg="do something"
      with_sequence: start=6379 end={{ 6379 + (redis_instances - 1) }}
      register: monit_redis_services

    - set_fact:
        mysequence: "{{ monit_redis_services.results | map(attribute='item') | list }}"

    - debug: var=mysequence
  when: ACTION == "create"

- name: Running Pre Workload Tasks
  include: ./pre_workload.yml
  become: true
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  include: ./workload.yml
  become: true
  when: ACTION == "create" or ACTION == "provision"

- name: Running Post Workload Tasks
  include: ./post_workload.yml
  become: true
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  include: ./remove_workload.yml
  become: true
  when: ACTION == "destroy" or ACTION == "remove"
