---

- debug:
    msg: "Setting up nfs for {{ required_pv.key }}"

- name: Iterate over required PVs and set up NFS
  include_tasks: setup_nfs_item.yml
  with_sequence: start=1 end={{ required_pv.value.size }} format={{ required_pv.key }}_%02x
  loop_control:
    loop_var: nfs_item
  notify:
    - restart nfs

#echo "/srv/nfs/user-vols/pv${pvnum} *(rw,root_squash)" >> /etc/exports.d/openshift-uservols.exports
#chown -R nfsnobody.nfsnobody  /srv/nfs
#chmod -R 777 /srv/nfs