---
#mkdir -p /srv/nfs/user-vols/pv{1..100}
#
#for pvnum in {1..100} ; do
#echo "/srv/nfs/user-vols/pv${pvnum} *(rw,root_squash)" >> /etc/exports.d/openshift-uservols.exports
#chown -R nfsnobody.nfsnobody  /srv/nfs
#chmod -R 777 /srv/nfs
#done
#
#systemctl restart nfs-server

- name: Confirm NFS exports dir is ready
  file:
    path: "{{ base_exports_dir }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Confirm NFS mobile exports table is ready
  file:
    path: "{{ base_exports_dir }}/{{ mobile_exports_table }}"
    state: touch
    mode: 755

- name: Confirm NFS dir is ready
  file:
    path: /srv/nfs/rhmap-vols/
    state: directory
    mode: 0755

- name: Iterate over required PVs and set up NFS
  include_tasks: setup_nfs.yml
  with_dict: "{{ required_pvs }}"
  loop_control:
    loop_var: required_pv

#- name: Prepare PVs
#  block:
#    - file:
#      path: /etc/exports.d/rhmap-vols.exports
#      state: touch
#      mode: 755
#
#    - file:
#      path: /srv/nfs/rhmap-vols/
#      state: directory
#      mode: 0755
#
#    - name: Iterate over required PVs
#      block:
#        - name: create directories
#          file:
#            path: /srv/nfs/rhmap-vols/
#            state: directory
#            mode: 0755
#            with_sequence: start=0 end={{ item.size }} format=pv%02x
#        - name: create exports file
#          lineinfile:
#          dest: /etc/exports.d/rhmap-vols.exports
#          line: '/srv/nfs/rhmap-vols/{{ item.key }} *(rw,root_squash,no_wdelay,sync)'
#          state: present
#          with_sequence: start=0 end={{  }} format=testuser%02x
#          notify: restart nfs services
#          run_once: True
#      with_dict: "{{ required_pvs }}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
